version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gooanalysis
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data




  flower:
    image: mher/flower
    container_name: flower
    command: celery flower # This will execute flower.
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - FLOWER_PORT=5555
    ports:
    - 5555:5555 # docker will expose this ports for flower
    depends_on:
      - redis
volumes:
    postgres-data:
    redis-data:

