version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gooanalysis
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=gooanalysis
      - MB_DB_PORT=5432
      - MB_DB_USER=user
      - MB_DB_PASS=password
      - MB_DB_HOST=db
    depends_on:
      - db
    volumes:
      - metabase-data:/metabase-data

  flower:
    image: mher/flower
    container_name: flower
    command: "celery --broker=redis://redis:6379/0 flower --port=5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
    - 5555:5555 # docker will expose this ports for flower
    depends_on:
      - redis
volumes:
    postgres-data:
    redis-data:
    metabase-data:
