---
local_machines:
  vars:
    ip_prefix: 10.0.0
  hosts:
    test:
      ansible_host: "{{  ip_prefix }}.5"
      ansible_user: alisha
      ansible_password: "{{ vault_local_ansible_password }}"
      ansible_become_pass: "{{ vault_local_become_ansible_password }}"

